export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST';
export const GET_POINTS_ERROR = 'GET_POINTS_ERROR';
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';

export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_DEPARTURE = 'SET_DEPARTURE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const GET_NEAREST_POINTS = 'GET_NEAREST_POINTS';